export function createUi() {
  return {
    label: document.getElementById('label'),
    back: document.getElementById('back'),
    clock: document.getElementById('clock'),
    clkTxt: document.getElementById('clkTxt'),
    timeTxt: document.getElementById('timeTxt'),
    timeUi: document.getElementById('timeUi'),
    init: document.getElementById('init'),
    loaderTxt: document.getElementById('loaderTxt'),
    hifiUi: document.getElementById('hifiUi'),
    tvUi: document.getElementById('tvUi'),
    winUi: document.getElementById('winUi'),
    holoUi: document.getElementById('holoUi'),
    musicPow: document.getElementById('musicPow'),
    musicPlay: document.getElementById('musicPlay'),
    musicPrev: document.getElementById('musicPrev'),
    musicNext: document.getElementById('musicNext'),
    tvPow: document.getElementById('tvPow'),
    winToggle: document.getElementById('winToggle'),
    winLean: document.getElementById('winLean')
  };
}

export function createState() {
  return {
    t: 0,
    lastTs: 0,
    mx: 0,
    my: 0,
    focus: null,
    hover: null,
    timeMode: 'auto',
    timeCycle: false,
    cycleAt: 0,
    cycleMinutesBase: 22 * 60 + 47,
    timeBlend: { day: 0, sunset: 0, night: 1 },
    currentMinutes: 22 * 60 + 47,
    weather: { rain: true, snow: false, mist: false, thunderstorm: false },
    mood: 'calm',
    winOpen: false,
    winAnim: 0,
    leanOut: false,
    lampOn: true,
    tvOn: true,
    tvCh: 3,
    tvFlicker: 0,
    musicOn: true,
    musicSource: 'vinyl',
    musicTrack: 0,
    vinylSpin: 0,
    holoPulse: 0,
    labelHold: 0,
    camX: 0,
    camY: 0,
    glowPulse: 0,
    cityOffset: 0,
    parallaxX: 0,
    parallaxY: 0,
    lightningFlash: 0,
    lightningNext: 8 + Math.random() * 20,
    helicopterX: -0.1,
    helicopterY: 0.18,
    helicopterActive: false,
    helicopterNext: 30 + Math.random() * 60,
    helicopterAngle: 0,
    condensation: Array.from({ length: 12 }, () => ({
      x: Math.random(),
      y: Math.random(),
      r: 8 + Math.random() * 24,
      clearing: false,
      alpha: 0.12 + Math.random() * 0.18,
      next: Math.random() * 30
    })),
    snow: [],
    rain: []
  };
}
